export const cards = {
  germany: [
    {
      author: 'Курт Вернер',
      title: 'Над городом',
      description: 'Цветная литография (40х60)',
      price: 16000,
      image: 'gr1.png',
    },
    {
      author: 'Макс Рихтер',
      title: 'Птенцы',
      description: 'Холст, масло (50х60)',
      price: 14500,
      image: 'gr2.png',
    },
    {
      author: 'Мартин Маейр',
      title: 'Среди листьев',
      description: 'Цветная литография (40х60)',
      price: 20000,
      image: 'gr3.png',
    },
    {
      author: 'Герман Беккер',
      title: 'Яркая птица',
      description: 'Цветная литография (40х60)',
      price: 13000,
      image: 'gr4.png',
    },
    {
      author: 'Вульф Бауэр',
      title: 'Дятлы',
      description: 'Бумага, акрил (50х80)',
      price: 20000,
      image: 'gr5.png',
    },
    {
      author: 'Вальтер Хартманн',
      title: 'Большие воды',
      description: 'Бумага, акрил (50х80)',
      price: 23000,
      image: 'gr6.png',
    },
  ],
  england: [
    {
      author: 'Пол Смит',
      title: 'Дикий зверь',
      description: 'Акварель, бумага (50х80)',
      price: 19500,
      image: 'en1.png',
    },
    {
      author: 'Джон Уайт',
      title: 'Скалистый берег',
      description: 'Цветная литография (40х60) ',
      price: 17500,
      image: 'en2.png',
    },
    {
      author: 'Джим Уотсон',
      title: 'Река и горы',
      description: 'Акварель, бумага (50х80)',
      price: 20500,
      image: 'en3.png',
    },
    {
      author: 'Юджин Зиллион',
      title: 'Белый попугай',
      description: 'Цветная литография (40х60)',
      price: 15500,
      image: 'en4.png',
    },
    {
      author: 'Эрик Гиллман',
      title: 'Ночная рыба',
      description: 'Бумага, акрил (50х80)',
      price: 12500,
      image: 'en5.png',
    },
    {
      author: 'Альфред Барр',
      title: 'Рыжий кот',
      description: 'Цветная литография (40х60)',
      price: 21000,
      image: 'en6.png',
    },
  ],
  france: [
    {
      author: 'Марсель Руссо',
      title: 'Охота Амура',
      description: 'Холст, масло (50х80)',
      price: 14500,
      image: 'fr1.png',
    },
    {
      author: 'Анри Селин',
      title: 'Дама с собачкой',
      description: 'Акрил, масло (50х80)',
      price: 16500,
      image: 'fr2.png',
    },
    {
      author: 'Франсуа Дюпон',
      title: 'Среди листьев',
      description: 'Цветная литография (40х60)',
      price: 20000,
      image: 'fr3.png',
    },
    {
      author: 'Луи Детуш',
      title: 'Роза',
      description: 'Бумага, акрил (50х80)',
      price: 12000,
      image: 'fr4.png',
    },
    {
      author: 'Франсуа Дюпон',
      title: 'Птичья трапеза',
      description: 'Цветная литография (40х60)',
      price: 22500,
      image: 'fr5.png',
    },
    {
      author: 'Пьер Моранж',
      title: 'Пейзаж с рыбой',
      description: 'Цветная литография (40х60)',
      price: 20000,
      image: 'fr6.png',
    },
  ],
}
